language: csharp
mono: none
dotnet: 2.0
solution: ./src/MCI.net.sln
install:
  - dotnet --version
script:
  - dotnet restore ./src/MCI.Core/MCI.Core.csproj --verbosity m
  - dotnet build ./src/MCI.Core/MCI.Core.csproj
  - dotnet restore ./src/MCI.Core.Tests/MCI.Core.Tests.csproj --verbosity m
  - cd src/MCI.Core.Tests
  - dotnet xunit
