version: 1.0.{build}
image: Visual Studio 2017
branches:
  except:
    - gh-pages


init:
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/MCI.Core/MCI.Core.csproj --verbosity m
  - cmd: dotnet restore ./src/MCI.Standard/MCI.Standard.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build ./src/MCI.Core/MCI.Core.csproj
  - cmd: dotnet build ./src/MCI.Standard/MCI.Standard.csproj
after_build:
  # For once the build has completed
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./src/MCI.Core.Tests/MCI.Core.Tests.csproj --verbosity m
  - cmd: cd src/MCI.Core.Tests
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off


notifications:
  - provider: Email
    to:
      - inahata@miharu.co.jp
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
