version: '3'

tasks:
  format:
    cmds:
      - dotnet format MCI.net.sln
      - dotnet format whitespace MCI.net.sln

  test:
    cmds:
      - dotnet test MCI.net.sln

  clean:
    cmds:
      - dotnet clean MCI.net.sln
